---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "circularmapper_realignsamfile"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::circularmapper=1.93.5"
