---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "arriba_visualisation"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::arriba=2.4.0"
