name: "pymygene"
description: Fetch the GO concepts for a list of genes
keywords:
  - mygene
  - go
  - annotation
tools:
  - "pymygene":
      description: "A python wrapper to query/retrieve gene annotation data from Mygene.info."
      homepage: "https://mygene.info/"
      documentation: "https://docs.mygene.info/projects/mygene-py/en/latest/"
      tool_dev_url: "https://github.com/biothings/mygene.py"
      doi: "10.1093/nar/gks1114"
      licence: ["Apache-2.0"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1' ]`
  - gene_list:
      type: file
      description: File containing a list of gene ids (ideally ensembl gene ids)
      pattern: "*.txt"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1' ]`
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: |
        A tsv file with the following columns: query, mygene_id, go_id, go_term, go_evidence, go_category, symbol, name, taxid
      pattern: "*.tsv"
  - gmt:
      type: file
      description: |
        Each row contains the GO id, a description, and a list of gene ids.
      pattern: "*.gmt"

authors:
  - "@suzannejin"
maintainers:
  - "@suzannejin"
